export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

/**
 * FUSION FORGE CREATIONS
 * AUTHORITATIVE SUPABASE DATABASE SCHEMA TYPES
 * Production Source of Truth
 */
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          email: string;
          role: 'super_admin' | 'admin' | 'editor' | 'accountant' | 'project_manager' | 'staff' | 'client';
          avatar_url: string | null;
          phone: string | null;
          designation: string | null;
          client_id: string | null;
          is_active: boolean;
          last_login_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          email: string;
          role?: 'super_admin' | 'admin' | 'editor' | 'accountant' | 'project_manager' | 'staff' | 'client';
          avatar_url?: string | null;
          phone?: string | null;
          designation?: string | null;
          client_id?: string | null;
          is_active?: boolean;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          email?: string;
          role?: 'super_admin' | 'admin' | 'editor' | 'accountant' | 'project_manager' | 'staff' | 'client';
          avatar_url?: string | null;
          phone?: string | null;
          designation?: string | null;
          client_id?: string | null;
          is_active?: boolean;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      permissions: {
        Row: {
          id: string;
          code: string;
          name: string;
          category: string;
          description: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          name: string;
          category: string;
          description?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          name?: string;
          category?: string;
          description?: string | null;
          created_at?: string;
        };
      };
      role_permissions: {
        Row: {
          id: string;
          role: string;
          permission_code: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          role: string;
          permission_code: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          role?: string;
          permission_code?: string;
          created_at?: string;
        };
      };
      services: {
        Row: {
          id: string;
          title: string;
          slug: string;
          description: string;
          icon: string;
          features: string[] | null;
          order_index: number | null;
          is_active: boolean | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          description: string;
          icon: string;
          features?: string[] | null;
          order_index?: number | null;
          is_active?: boolean | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          description?: string;
          icon?: string;
          features?: string[] | null;
          order_index?: number | null;
          is_active?: boolean | null;
          created_at?: string;
        };
      };
      service_price_presets: {
        Row: {
          id: string;
          service_id: string | null;
          name: string;
          sac_code: string;
          default_rate: number;
          unit: string;
          description: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          service_id?: string | null;
          name: string;
          sac_code?: string;
          default_rate?: number;
          unit?: string;
          description?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          service_id?: string | null;
          name?: string;
          sac_code?: string;
          default_rate?: number;
          unit?: string;
          description?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      projects: {
        Row: {
          id: string;
          title: string;
          slug: string;
          client_name: string | null;
          service_id: string | null;
          description: string;
          image_url: string | null;
          live_url: string | null;
          technologies: string[] | null;
          featured: boolean | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          client_name?: string | null;
          service_id?: string | null;
          description: string;
          image_url?: string | null;
          live_url?: string | null;
          technologies?: string[] | null;
          featured?: boolean | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          client_name?: string | null;
          service_id?: string | null;
          description?: string;
          image_url?: string | null;
          live_url?: string | null;
          technologies?: string[] | null;
          featured?: boolean | null;
          created_at?: string;
        };
      };
      managed_projects: {
        Row: {
          id: string;
          title: string;
          client_id: string;
          quotation_id: string | null;
          project_manager_id: string | null;
          status: 'planning' | 'in_progress' | 'review' | 'completed' | 'on_hold' | 'cancelled';
          progress_percentage: number;
          staging_url: string | null;
          production_url: string | null;
          start_date: string | null;
          target_completion_date: string | null;
          actual_completion_date: string | null;
          budget: number | null;
          description: string | null;
          deliverables: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          client_id: string;
          quotation_id?: string | null;
          project_manager_id?: string | null;
          status?: 'planning' | 'in_progress' | 'review' | 'completed' | 'on_hold' | 'cancelled';
          progress_percentage?: number;
          staging_url?: string | null;
          production_url?: string | null;
          start_date?: string | null;
          target_completion_date?: string | null;
          actual_completion_date?: string | null;
          budget?: number | null;
          description?: string | null;
          deliverables?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          client_id?: string;
          quotation_id?: string | null;
          project_manager_id?: string | null;
          status?: 'planning' | 'in_progress' | 'review' | 'completed' | 'on_hold' | 'cancelled';
          progress_percentage?: number;
          staging_url?: string | null;
          production_url?: string | null;
          start_date?: string | null;
          target_completion_date?: string | null;
          actual_completion_date?: string | null;
          budget?: number | null;
          description?: string | null;
          deliverables?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      project_status_history: {
        Row: {
          id: string;
          project_id: string;
          previous_status: string;
          new_status: string;
          changed_by: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          previous_status: string;
          new_status: string;
          changed_by?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          previous_status?: string;
          new_status?: string;
          changed_by?: string | null;
          notes?: string | null;
          created_at?: string;
        };
      };
      technologies: {
        Row: {
          id: string;
          name: string;
          category: string;
          logo_url: string | null;
          is_active: boolean | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          category: string;
          logo_url?: string | null;
          is_active?: boolean | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          category?: string;
          logo_url?: string | null;
          is_active?: boolean | null;
          created_at?: string;
        };
      };
      testimonials: {
        Row: {
          id: string;
          client_name: string;
          client_title: string | null;
          company: string;
          avatar_url: string | null;
          content: string;
          rating: number;
          is_featured: boolean | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          client_name: string;
          client_title?: string | null;
          company: string;
          avatar_url?: string | null;
          content: string;
          rating?: number;
          is_featured?: boolean | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          client_name?: string;
          client_title?: string | null;
          company?: string;
          avatar_url?: string | null;
          content?: string;
          rating?: number;
          is_featured?: boolean | null;
          created_at?: string;
        };
      };
      faqs: {
        Row: {
          id: string;
          question: string;
          answer: string;
          category: string | null;
          order_index: number | null;
          is_active: boolean | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          question: string;
          answer: string;
          category?: string | null;
          order_index?: number | null;
          is_active?: boolean | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          question?: string;
          answer?: string;
          category?: string | null;
          order_index?: number | null;
          is_active?: boolean | null;
          created_at?: string;
        };
      };
      enquiries: {
        Row: {
          id: string;
          name: string;
          company: string | null;
          email: string;
          phone: string | null;
          project_type: string;
          budget: string | null;
          timeline: string | null;
          message: string;
          status: 'New' | 'Contacted' | 'Discussion' | 'Proposal' | 'Won' | 'Lost' | 'Converted' | 'Closed' | 'Junk';
          source: string | null;
          priority: string | null;
          estimated_value: number | null;
          service_category: string | null;
          assigned_to: string | null;
          converted_client_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          company?: string | null;
          email: string;
          phone?: string | null;
          project_type: string;
          budget?: string | null;
          timeline?: string | null;
          message: string;
          status?: 'New' | 'Contacted' | 'Discussion' | 'Proposal' | 'Won' | 'Lost' | 'Converted' | 'Closed' | 'Junk';
          source?: string | null;
          priority?: string | null;
          estimated_value?: number | null;
          service_category?: string | null;
          assigned_to?: string | null;
          converted_client_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          company?: string | null;
          email?: string;
          phone?: string | null;
          project_type?: string;
          budget?: string | null;
          timeline?: string | null;
          message?: string;
          status?: 'New' | 'Contacted' | 'Discussion' | 'Proposal' | 'Won' | 'Lost' | 'Converted' | 'Closed' | 'Junk';
          source?: string | null;
          priority?: string | null;
          estimated_value?: number | null;
          service_category?: string | null;
          assigned_to?: string | null;
          converted_client_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      lead_status_history: {
        Row: {
          id: string;
          enquiry_id: string;
          previous_status: string;
          new_status: string;
          changed_by: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          enquiry_id: string;
          previous_status: string;
          new_status: string;
          changed_by?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          enquiry_id?: string;
          previous_status?: string;
          new_status?: string;
          changed_by?: string | null;
          notes?: string | null;
          created_at?: string;
        };
      };
      clients: {
        Row: {
          id: string;
          name: string;
          company: string | null;
          email: string;
          phone: string | null;
          address: string | null;
          tax_number: string | null;
          gstin: string | null;
          pan: string | null;
          notes: string | null;
          enquiry_id: string | null;
          state_code: string | null;
          place_of_supply: string | null;
          billing_address_line1: string | null;
          billing_address_line2: string | null;
          billing_city: string | null;
          billing_state: string | null;
          billing_state_code: string | null;
          billing_pincode: string | null;
          shipping_address_line1: string | null;
          shipping_address_line2: string | null;
          shipping_city: string | null;
          shipping_state: string | null;
          shipping_state_code: string | null;
          shipping_pincode: string | null;
          is_shipping_same_as_billing: boolean;
          is_deleted: boolean;
          deleted_at: string | null;
          deleted_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          company?: string | null;
          email: string;
          phone?: string | null;
          address?: string | null;
          tax_number?: string | null;
          gstin?: string | null;
          pan?: string | null;
          notes?: string | null;
          enquiry_id?: string | null;
          state_code?: string | null;
          place_of_supply?: string | null;
          billing_address_line1?: string | null;
          billing_address_line2?: string | null;
          billing_city?: string | null;
          billing_state?: string | null;
          billing_state_code?: string | null;
          billing_pincode?: string | null;
          shipping_address_line1?: string | null;
          shipping_address_line2?: string | null;
          shipping_city?: string | null;
          shipping_state?: string | null;
          shipping_state_code?: string | null;
          shipping_pincode?: string | null;
          is_shipping_same_as_billing?: boolean;
          is_deleted?: boolean;
          deleted_at?: string | null;
          deleted_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          company?: string | null;
          email?: string;
          phone?: string | null;
          address?: string | null;
          tax_number?: string | null;
          gstin?: string | null;
          pan?: string | null;
          notes?: string | null;
          enquiry_id?: string | null;
          state_code?: string | null;
          place_of_supply?: string | null;
          billing_address_line1?: string | null;
          billing_address_line2?: string | null;
          billing_city?: string | null;
          billing_state?: string | null;
          billing_state_code?: string | null;
          billing_pincode?: string | null;
          shipping_address_line1?: string | null;
          shipping_address_line2?: string | null;
          shipping_city?: string | null;
          shipping_state?: string | null;
          shipping_state_code?: string | null;
          shipping_pincode?: string | null;
          is_shipping_same_as_billing?: boolean;
          is_deleted?: boolean;
          deleted_at?: string | null;
          deleted_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      quotations: {
        Row: {
          id: string;
          quote_number: string;
          client_id: string;
          client_company: string | null;
          client_name: string | null;
          client_email: string | null;
          client_gstin: string | null;
          place_of_supply: string | null;
          place_of_supply_code: string | null;
          title: string;
          status: 'draft' | 'sent' | 'accepted' | 'rejected' | 'converted' | 'expired';
          issue_date: string;
          valid_until: string;
          subtotal: number;
          discount_type: string | null;
          discount_value: number | null;
          discount_amount: number;
          taxable_amount: number;
          supply_type: string | null;
          gst_applicable: boolean;
          gst_type: string | null;
          tax_rate: number;
          cgst_amount: number;
          sgst_amount: number;
          utgst_amount: number;
          igst_amount: number;
          tax_amount: number;
          grand_total: number;
          amount_in_words: string | null;
          terms_conditions: string | null;
          notes: string | null;
          converted_invoice_id: string | null;
          order_received_at: string | null;
          po_reference_number: string | null;
          is_deleted: boolean;
          deleted_at: string | null;
          deleted_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          quote_number: string;
          client_id: string;
          client_company?: string | null;
          client_name?: string | null;
          client_email?: string | null;
          client_gstin?: string | null;
          place_of_supply?: string | null;
          place_of_supply_code?: string | null;
          title: string;
          status?: 'draft' | 'sent' | 'accepted' | 'rejected' | 'converted' | 'expired';
          issue_date?: string;
          valid_until?: string;
          subtotal?: number;
          discount_type?: string | null;
          discount_value?: number | null;
          discount_amount?: number;
          taxable_amount?: number;
          supply_type?: string | null;
          gst_applicable?: boolean;
          gst_type?: string | null;
          tax_rate?: number;
          cgst_amount?: number;
          sgst_amount?: number;
          utgst_amount?: number;
          igst_amount?: number;
          tax_amount?: number;
          grand_total?: number;
          amount_in_words?: string | null;
          terms_conditions?: string | null;
          notes?: string | null;
          converted_invoice_id?: string | null;
          order_received_at?: string | null;
          po_reference_number?: string | null;
          is_deleted?: boolean;
          deleted_at?: string | null;
          deleted_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          quote_number?: string;
          client_id?: string;
          client_company?: string | null;
          client_name?: string | null;
          client_email?: string | null;
          client_gstin?: string | null;
          place_of_supply?: string | null;
          place_of_supply_code?: string | null;
          title?: string;
          status?: 'draft' | 'sent' | 'accepted' | 'rejected' | 'converted' | 'expired';
          issue_date?: string;
          valid_until?: string;
          subtotal?: number;
          discount_type?: string | null;
          discount_value?: number | null;
          discount_amount?: number;
          taxable_amount?: number;
          supply_type?: string | null;
          gst_applicable?: boolean;
          gst_type?: string | null;
          tax_rate?: number;
          cgst_amount?: number;
          sgst_amount?: number;
          utgst_amount?: number;
          igst_amount?: number;
          tax_amount?: number;
          grand_total?: number;
          amount_in_words?: string | null;
          terms_conditions?: string | null;
          notes?: string | null;
          converted_invoice_id?: string | null;
          order_received_at?: string | null;
          po_reference_number?: string | null;
          is_deleted?: boolean;
          deleted_at?: string | null;
          deleted_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      quotation_items: {
        Row: {
          id: string;
          quotation_id: string;
          service_id: string | null;
          description: string;
          sac_code: string;
          quantity: number;
          unit: string;
          unit_price: number;
          total_price: number;
        };
        Insert: {
          id?: string;
          quotation_id: string;
          service_id?: string | null;
          description: string;
          sac_code?: string;
          quantity?: number;
          unit?: string;
          unit_price?: number;
          total_price?: number;
        };
        Update: {
          id?: string;
          quotation_id?: string;
          service_id?: string | null;
          description?: string;
          sac_code?: string;
          quantity?: number;
          unit?: string;
          unit_price?: number;
          total_price?: number;
        };
      };
      quotation_status_history: {
        Row: {
          id: string;
          quotation_id: string;
          previous_status: string;
          new_status: string;
          changed_by: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          quotation_id: string;
          previous_status: string;
          new_status: string;
          changed_by?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          quotation_id?: string;
          previous_status?: string;
          new_status?: string;
          changed_by?: string | null;
          notes?: string | null;
          created_at?: string;
        };
      };
      invoices: {
        Row: {
          id: string;
          invoice_number: string;
          quotation_id: string | null;
          client_id: string;
          status: 'Draft' | 'Sent' | 'Partially Paid' | 'Paid' | 'Overdue' | 'Cancelled';
          issue_date: string;
          due_date: string;
          subtotal: number;
          discount: number;
          tax_rate: number;
          tax_amount: number;
          grand_total: number;
          paid_amount: number;
          notes: string | null;
          terms: string | null;
          taxable_amount: number;
          gst_applicable: boolean;
          seller_gstin: string | null;
          seller_state_code: string | null;
          buyer_gstin: string | null;
          buyer_state_code: string | null;
          place_of_supply: string | null;
          reverse_charge: string | null;
          invoice_type: string | null;
          irn: string | null;
          ack_no: string | null;
          ack_date: string | null;
          qr_code_data: string | null;
          cgst_amount: number;
          sgst_amount: number;
          utgst_amount: number;
          igst_amount: number;
          is_deleted: boolean;
          deleted_at: string | null;
          deleted_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          invoice_number: string;
          quotation_id?: string | null;
          client_id: string;
          status?: 'Draft' | 'Sent' | 'Partially Paid' | 'Paid' | 'Overdue' | 'Cancelled';
          issue_date?: string;
          due_date: string;
          subtotal?: number;
          discount?: number;
          tax_rate?: number;
          tax_amount?: number;
          grand_total?: number;
          paid_amount?: number;
          notes?: string | null;
          terms?: string | null;
          taxable_amount?: number;
          gst_applicable?: boolean;
          seller_gstin?: string | null;
          seller_state_code?: string | null;
          buyer_gstin?: string | null;
          buyer_state_code?: string | null;
          place_of_supply?: string | null;
          reverse_charge?: string | null;
          invoice_type?: string | null;
          irn?: string | null;
          ack_no?: string | null;
          ack_date?: string | null;
          qr_code_data?: string | null;
          cgst_amount?: number;
          sgst_amount?: number;
          utgst_amount?: number;
          igst_amount?: number;
          is_deleted?: boolean;
          deleted_at?: string | null;
          deleted_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          invoice_number?: string;
          quotation_id?: string | null;
          client_id?: string;
          status?: 'Draft' | 'Sent' | 'Partially Paid' | 'Paid' | 'Overdue' | 'Cancelled';
          issue_date?: string;
          due_date?: string;
          subtotal?: number;
          discount?: number;
          tax_rate?: number;
          tax_amount?: number;
          grand_total?: number;
          paid_amount?: number;
          notes?: string | null;
          terms?: string | null;
          taxable_amount?: number;
          gst_applicable?: boolean;
          seller_gstin?: string | null;
          seller_state_code?: string | null;
          buyer_gstin?: string | null;
          buyer_state_code?: string | null;
          place_of_supply?: string | null;
          reverse_charge?: string | null;
          invoice_type?: string | null;
          irn?: string | null;
          ack_no?: string | null;
          ack_date?: string | null;
          qr_code_data?: string | null;
          cgst_amount?: number;
          sgst_amount?: number;
          utgst_amount?: number;
          igst_amount?: number;
          is_deleted?: boolean;
          deleted_at?: string | null;
          deleted_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      invoice_items: {
        Row: {
          id: string;
          invoice_id: string;
          description: string;
          sac_code: string | null;
          quantity: number;
          unit_price: number;
          total_price: number;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          description: string;
          sac_code?: string | null;
          quantity?: number;
          unit_price?: number;
          total_price?: number;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          description?: string;
          sac_code?: string | null;
          quantity?: number;
          unit_price?: number;
          total_price?: number;
        };
      };
      payments: {
        Row: {
          id: string;
          receipt_number: string | null;
          invoice_id: string;
          client_id: string | null;
          amount: number;
          payment_date: string;
          payment_method: string;
          transaction_ref: string | null;
          tds_deducted: number;
          bank_charges: number;
          net_amount_received: number;
          notes: string | null;
          recorded_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          receipt_number?: string | null;
          invoice_id: string;
          client_id?: string | null;
          amount: number;
          payment_date?: string;
          payment_method?: string;
          transaction_ref?: string | null;
          tds_deducted?: number;
          bank_charges?: number;
          net_amount_received?: number;
          notes?: string | null;
          recorded_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          receipt_number?: string | null;
          invoice_id?: string;
          client_id?: string | null;
          amount?: number;
          payment_date?: string;
          payment_method?: string;
          transaction_ref?: string | null;
          tds_deducted?: number;
          bank_charges?: number;
          net_amount_received?: number;
          notes?: string | null;
          recorded_by?: string | null;
          created_at?: string;
        };
      };
      credit_notes: {
        Row: {
          id: string;
          note_number: string;
          original_invoice_id: string;
          client_id: string;
          reason: string;
          taxable_amount: number;
          cgst_amount: number;
          sgst_amount: number;
          utgst_amount: number;
          igst_amount: number;
          total_amount: number;
          note_date: string;
          status: 'issued' | 'applied' | 'cancelled';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          note_number: string;
          original_invoice_id: string;
          client_id: string;
          reason: string;
          taxable_amount?: number;
          cgst_amount?: number;
          sgst_amount?: number;
          utgst_amount?: number;
          igst_amount?: number;
          total_amount?: number;
          note_date?: string;
          status?: 'issued' | 'applied' | 'cancelled';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          note_number?: string;
          original_invoice_id?: string;
          client_id?: string;
          reason?: string;
          taxable_amount?: number;
          cgst_amount?: number;
          sgst_amount?: number;
          utgst_amount?: number;
          igst_amount?: number;
          total_amount?: number;
          note_date?: string;
          status?: 'issued' | 'applied' | 'cancelled';
          created_at?: string;
          updated_at?: string;
        };
      };
      debit_notes: {
        Row: {
          id: string;
          note_number: string;
          original_invoice_id: string;
          client_id: string;
          reason: string;
          taxable_amount: number;
          cgst_amount: number;
          sgst_amount: number;
          utgst_amount: number;
          igst_amount: number;
          total_amount: number;
          note_date: string;
          status: 'issued' | 'applied' | 'cancelled';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          note_number: string;
          original_invoice_id: string;
          client_id: string;
          reason: string;
          taxable_amount?: number;
          cgst_amount?: number;
          sgst_amount?: number;
          utgst_amount?: number;
          igst_amount?: number;
          total_amount?: number;
          note_date?: string;
          status?: 'issued' | 'applied' | 'cancelled';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          note_number?: string;
          original_invoice_id?: string;
          client_id?: string;
          reason?: string;
          taxable_amount?: number;
          cgst_amount?: number;
          sgst_amount?: number;
          utgst_amount?: number;
          igst_amount?: number;
          total_amount?: number;
          note_date?: string;
          status?: 'issued' | 'applied' | 'cancelled';
          created_at?: string;
          updated_at?: string;
        };
      };
      expenses: {
        Row: {
          id: string;
          title: string;
          category: string;
          amount: number;
          expense_date: string;
          vendor_name: string | null;
          vendor_gstin: string | null;
          hsn_sac: string | null;
          payment_method: string | null;
          receipt_url: string | null;
          is_recurring: boolean;
          taxable_amount: number;
          gst_rate: number;
          cgst_amount: number;
          sgst_amount: number;
          igst_amount: number;
          itc_eligible: boolean;
          notes: string | null;
          recorded_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          category: string;
          amount: number;
          expense_date?: string;
          vendor_name?: string | null;
          vendor_gstin?: string | null;
          hsn_sac?: string | null;
          payment_method?: string | null;
          receipt_url?: string | null;
          is_recurring?: boolean;
          taxable_amount?: number;
          gst_rate?: number;
          cgst_amount?: number;
          sgst_amount?: number;
          igst_amount?: number;
          itc_eligible?: boolean;
          notes?: string | null;
          recorded_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          category?: string;
          amount?: number;
          expense_date?: string;
          vendor_name?: string | null;
          vendor_gstin?: string | null;
          hsn_sac?: string | null;
          payment_method?: string | null;
          receipt_url?: string | null;
          is_recurring?: boolean;
          taxable_amount?: number;
          gst_rate?: number;
          cgst_amount?: number;
          sgst_amount?: number;
          igst_amount?: number;
          itc_eligible?: boolean;
          notes?: string | null;
          recorded_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      salary_entries: {
        Row: {
          id: string;
          staff_id: string;
          staff_name: string;
          designation: string;
          month_year: string;
          basic_salary: number;
          allowances: number;
          gross_salary: number;
          pf_deduction: number;
          professional_tax: number;
          tds_deduction: number;
          other_deductions: number;
          net_salary: number;
          disbursement_date: string | null;
          disbursement_status: 'draft' | 'approved' | 'disbursed';
          payment_mode: string | null;
          transaction_reference: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          staff_id: string;
          staff_name: string;
          designation: string;
          month_year: string;
          basic_salary?: number;
          allowances?: number;
          gross_salary?: number;
          pf_deduction?: number;
          professional_tax?: number;
          tds_deduction?: number;
          other_deductions?: number;
          net_salary?: number;
          disbursement_date?: string | null;
          disbursement_status?: 'draft' | 'approved' | 'disbursed';
          payment_mode?: string | null;
          transaction_reference?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          staff_id?: string;
          staff_name?: string;
          designation?: string;
          month_year?: string;
          basic_salary?: number;
          allowances?: number;
          gross_salary?: number;
          pf_deduction?: number;
          professional_tax?: number;
          tds_deduction?: number;
          other_deductions?: number;
          net_salary?: number;
          disbursement_date?: string | null;
          disbursement_status?: 'draft' | 'approved' | 'disbursed';
          payment_mode?: string | null;
          transaction_reference?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          type: string;
          category: string;
          title: string;
          message: string;
          link: string | null;
          entity_type: string | null;
          entity_id: string | null;
          priority: string;
          is_read: boolean;
          read_at: string | null;
          target_role: string;
          target_user_id: string | null;
          target_client_id: string | null;
          metadata: Json;
          event_key: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          type: string;
          category?: string;
          title: string;
          message: string;
          link?: string | null;
          entity_type?: string | null;
          entity_id?: string | null;
          priority?: string;
          is_read?: boolean;
          read_at?: string | null;
          target_role?: string;
          target_user_id?: string | null;
          target_client_id?: string | null;
          metadata?: Json;
          event_key?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          type?: string;
          category?: string;
          title?: string;
          message?: string;
          link?: string | null;
          entity_type?: string | null;
          entity_id?: string | null;
          priority?: string;
          is_read?: boolean;
          read_at?: string | null;
          target_role?: string;
          target_user_id?: string | null;
          target_client_id?: string | null;
          metadata?: Json;
          event_key?: string | null;
          created_at?: string;
        };
      };
      email_logs: {
        Row: {
          id: string;
          recipient: string;
          sender: string;
          subject: string;
          category: string;
          status: string;
          message_id: string | null;
          error_message: string | null;
          entity_type: string | null;
          entity_id: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          recipient: string;
          sender?: string;
          subject: string;
          category?: string;
          status?: string;
          message_id?: string | null;
          error_message?: string | null;
          entity_type?: string | null;
          entity_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          recipient?: string;
          sender?: string;
          subject?: string;
          category?: string;
          status?: string;
          message_id?: string | null;
          error_message?: string | null;
          entity_type?: string | null;
          entity_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
      };
      chatbot_qa: {
        Row: {
          id: string;
          question: string;
          answer: string;
          category: string;
          tags: string[] | null;
          is_active: boolean;
          order_index: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          question: string;
          answer: string;
          category?: string;
          tags?: string[] | null;
          is_active?: boolean;
          order_index?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          question?: string;
          answer?: string;
          category?: string;
          tags?: string[] | null;
          is_active?: boolean;
          order_index?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      chatbot_settings: {
        Row: {
          id: string;
          bot_name: string;
          welcome_message: string;
          fallback_message: string;
          is_enabled: boolean;
          lead_capture_enabled: boolean;
          updated_at: string;
        };
        Insert: {
          id?: string;
          bot_name?: string;
          welcome_message?: string;
          fallback_message?: string;
          is_enabled?: boolean;
          lead_capture_enabled?: boolean;
          updated_at?: string;
        };
        Update: {
          id?: string;
          bot_name?: string;
          welcome_message?: string;
          fallback_message?: string;
          is_enabled?: boolean;
          lead_capture_enabled?: boolean;
          updated_at?: string;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          user_id: string;
          user_email: string;
          user_role: string;
          action: string;
          table_name: string;
          record_id: string;
          details: string;
          ip_address: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          user_email: string;
          user_role: string;
          action: string;
          table_name: string;
          record_id: string;
          details: string;
          ip_address?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          user_email?: string;
          user_role?: string;
          action?: string;
          table_name?: string;
          record_id?: string;
          details?: string;
          ip_address?: string | null;
          created_at?: string;
        };
      };
      visitor_logs: {
        Row: {
          id: string;
          session_id: string;
          event_type: string;
          page_path: string;
          page_title: string | null;
          referrer: string | null;
          device_type: string | null;
          browser: string | null;
          os: string | null;
          screen_resolution: string | null;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          session_id: string;
          event_type: string;
          page_path: string;
          page_title?: string | null;
          referrer?: string | null;
          device_type?: string | null;
          browser?: string | null;
          os?: string | null;
          screen_resolution?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          session_id?: string;
          event_type?: string;
          page_path?: string;
          page_title?: string | null;
          referrer?: string | null;
          device_type?: string | null;
          browser?: string | null;
          os?: string | null;
          screen_resolution?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          metadata?: Json | null;
          created_at?: string;
        };
      };
      compliance_logs: {
        Row: {
          id: string;
          user_id: string | null;
          session_id: string | null;
          document_type: string;
          document_version: string;
          consent_given: boolean;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          session_id?: string | null;
          document_type: string;
          document_version: string;
          consent_given?: boolean;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          session_id?: string | null;
          document_type?: string;
          document_version?: string;
          consent_given?: boolean;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
      };
      website_settings: {
        Row: {
          id: string;
          setting_key: string;
          setting_value: Json;
          is_public: boolean;
          updated_at: string;
        };
        Insert: {
          id?: string;
          setting_key: string;
          setting_value: Json;
          is_public?: boolean;
          updated_at?: string;
        };
        Update: {
          id?: string;
          setting_key?: string;
          setting_value?: Json;
          is_public?: boolean;
          updated_at?: string;
        };
      };
      state_ut_master: {
        Row: {
          code: string;
          name: string;
          type: 'STATE' | 'UT';
          is_selectable: boolean;
        };
        Insert: {
          code: string;
          name: string;
          type: 'STATE' | 'UT';
          is_selectable?: boolean;
        };
        Update: {
          code?: string;
          name?: string;
          type?: 'STATE' | 'UT';
          is_selectable?: boolean;
        };
      };
      seller_profile: {
        Row: {
          id: string;
          company_name: string;
          legal_name: string | null;
          trade_name: string | null;
          tagline: string | null;
          email: string | null;
          phone: string | null;
          address: string | null;
          gstin: string | null;
          pan: string | null;
          msme_number: string | null;
          lut_number: string | null;
          lut_expiry_date: string | null;
          sac_code: string | null;
          state_code: string | null;
          jurisdiction: string | null;
          logo_url: string | null;
          signature_url: string | null;
          stamp_url: string | null;
          bank_name: string | null;
          account_name: string | null;
          account_number: string | null;
          ifsc_code: string | null;
          branch_name: string | null;
          upi_id: string | null;
          qr_code_url: string | null;
          invoice_prefix: string | null;
          quotation_prefix: string | null;
          receipt_prefix: string | null;
          default_payment_terms: string | null;
          default_quotation_terms: string | null;
          default_notes: string | null;
          terms_conditions: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_name: string;
          legal_name?: string | null;
          trade_name?: string | null;
          tagline?: string | null;
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          gstin?: string | null;
          pan?: string | null;
          msme_number?: string | null;
          lut_number?: string | null;
          lut_expiry_date?: string | null;
          sac_code?: string | null;
          state_code?: string | null;
          jurisdiction?: string | null;
          logo_url?: string | null;
          signature_url?: string | null;
          stamp_url?: string | null;
          bank_name?: string | null;
          account_name?: string | null;
          account_number?: string | null;
          ifsc_code?: string | null;
          branch_name?: string | null;
          upi_id?: string | null;
          qr_code_url?: string | null;
          invoice_prefix?: string | null;
          quotation_prefix?: string | null;
          receipt_prefix?: string | null;
          default_payment_terms?: string | null;
          default_quotation_terms?: string | null;
          default_notes?: string | null;
          terms_conditions?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_name?: string;
          legal_name?: string | null;
          trade_name?: string | null;
          tagline?: string | null;
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          gstin?: string | null;
          pan?: string | null;
          msme_number?: string | null;
          lut_number?: string | null;
          lut_expiry_date?: string | null;
          sac_code?: string | null;
          state_code?: string | null;
          jurisdiction?: string | null;
          logo_url?: string | null;
          signature_url?: string | null;
          stamp_url?: string | null;
          bank_name?: string | null;
          account_name?: string | null;
          account_number?: string | null;
          ifsc_code?: string | null;
          branch_name?: string | null;
          upi_id?: string | null;
          qr_code_url?: string | null;
          invoice_prefix?: string | null;
          quotation_prefix?: string | null;
          receipt_prefix?: string | null;
          default_payment_terms?: string | null;
          default_quotation_terms?: string | null;
          default_notes?: string | null;
          terms_conditions?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Functions: {
      get_user_role: {
        Args: { user_id: string };
        Returns: string;
      };
      generate_invoice_number: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
      generate_quotation_number: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
      extract_gst_state_code: {
        Args: { p_gstin: string };
        Returns: string;
      };
      recalculate_invoice_totals: {
        Args: { target_inv_id: string };
        Returns: void;
      };
      recalculate_quotation_totals: {
        Args: { target_qt_id: string };
        Returns: void;
      };
      update_overdue_invoices: {
        Args: Record<PropertyKey, never>;
        Returns: void;
      };
      create_invoice_with_items: {
        Args: {
          p_invoice_data: Json;
          p_items_data: Json;
        };
        Returns: Json;
      };
    };
  };
}
